import { config } from 'dotenv'
config({ path: '.env.local' })
import postgres from 'postgres'
import { randomUUID } from 'crypto'

type PostData = {
  communityKey: string
  title: string
  body: string
  roleTitle: string
  interviewStage: 'SCREEN' | 'PHONE' | 'ONSITE' | 'FINAL' | 'OFFER_RESCINDED'
  rejectionYear: number
  userIndex: number
}

const COMMUNITY_IDS: Record<string, string> = {
  'google/swe': 'ec6082da-db30-4d9d-b98c-b384baab0aba',
  'amazon/swe': '1ca35bdb-1aa7-4441-8b19-bb54164df217',
  'meta/swe': 'e8a957d6-123c-4189-b45b-e0c6c40041cc',
  'apple/swe': 'b08dd3bb-b824-4fc1-9085-9afdf79148be',
  'stripe/swe': '72f8f0d4-b6d4-4237-8e48-b2b882ec3a90',
  'netflix/swe': '2f038046-fe95-42bf-b0a7-c7b75e27e1f0',
  'microsoft/swe': '931e9359-e669-40c4-9df9-77309ba74fea',
  'airbnb/swe': 'b6306ef6-8d92-43db-9589-fd588f58d7f3',
  'shopify/swe': '00eb40de-6c34-4f7f-8eb0-65d42c2b811b',
  'figma/swe': 'a349cccb-9bf1-466b-a460-5233acbced50',
  'datadog/swe': 'ddbba17f-5894-49b3-8ca8-ee110da89092',
  'linkedin/swe': '52a3bbed-653b-496c-90e7-429fab4dc23c',
  'uber/swe': '8c649046-9e7e-4e18-a03b-4be17cd4ca43',
  'openai/swe': '6266a4cb-3d07-4a4c-a55c-cb6ef51fdfd0',
  'coinbase/swe': 'a7683e91-f06d-4c2f-b602-abd8859f7a6f',
  'bytedance/swe': '58687d27-b1ef-4937-a003-f6d7e5e82f05',
  'palantir/swe': 'e586a551-c997-4d8e-a4ad-30b03d29e8c8',
  'doordash/swe': '3bfcc8ad-4bd9-4932-b62b-14b6d3f4c468',
  'notion/swe': '429978c7-aa4a-4037-a024-aa1d29a84954',
  'databricks/swe': 'ddbba17f-5894-49b3-8ca8-ee110da89092',
  'ramp/swe': '67fcdb06-f3ae-44de-bc3e-fc17a0499064',
  'brex/swe': '45dda29e-d16f-4d9f-bfe0-8c03074dd155',
  'twitter/swe': '2c6c407d-aea3-4a15-8138-240adc711be1',
  'github/swe': '0162f7f8-8bab-4686-a338-f3419e3ca964',
  'yc/s25': '',
}

const SEED_USERS = [
  'throwaway_swe_loop', 'anon_new_grad_24', 'senior_ic_rant', 'invisible_engineer',
  'rejected_not_dejected', 'faang_or_bust_anon', 'staff_eng_lurker', 'bootcamp_to_bigtech',
  'ml_swe_crossover', 'laid_off_optimist', 'silent_grinder_99', 'pragmatic_dev_anon',
  'midnight_code_anon', 'founder_to_ic_again', 'forever_a_candidate',
]

const POSTS: PostData[] = [
  // ── GOOGLE ──
  { communityKey:'google/swe', title:'Four rounds, one No Hire on a graph problem, and that was the whole loop', body:`**Company**: Google\n**Position**: Senior SWE\n**Stage**: Onsite (4 rounds)\n**Self-Analysis**: One sub-optimal solution on a single round sank an otherwise strong loop.\n\n---\n\nI interviewed for a Senior SWE role at one of Google's European offices earlier this year. Four rounds. Round 1 came back Strongly Hire. Round 2 was a Hire with a readability note. Round 4 was another Strongly Hire. On paper that is three positive signals and a clear pattern.\n\nThen there is Round 3. A graph traversal problem. I found a working solution but not the optimal one — I burned too long on an approach that traversed redundantly instead of pruning early. The interviewer was patient, but I could feel myself reaching for cleverness when I should have been reaching for the obvious. That round came back No Hire.\n\nAnd that was it. One No Hire against three strong rounds, and the committee passed. I kept expecting the aggregate to matter more than the worst data point, but that is not how the bar works here. A single clear miss on problem-solving is enough.\n\nThe recruiter was genuinely kind about it. She told me the vast majority of people fail their first attempt, that the bar is calibrated to be unforgiving on exactly this kind of round, and that I should come back. I believe her, and it still stung.\n\nWhat I am taking from it: optimal beats working, and on the graph round I should have stated the brute force, named the inefficiency out loud, and only then optimized — instead of silently chasing elegance. The loop does not average. It looks for the floor.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior SWE', interviewStage:'ONSITE', rejectionYear:2024, userIndex:0 },
  { communityKey:'google/swe', title:'Three Strong Hires, made it to team matching, then the HC said no', body:`**Company**: Google\n**Position**: Junior SWE\n**Stage**: Onsite + Team Matching\n**Self-Analysis**: Strong technicals, but one soft Googlyness signal followed me to committee.\n\n---\n\nThis was for a junior SWE role in a Southeast Asia office. Four rounds, three came back Strong Hire. The fourth was a Lean Hire — solid code, but the interviewer flagged that my collaboration signal felt thin. Not hostile, just not warm.\n\nI moved to team matching, which I read as near-certain. People kept telling me team matching means you are basically through.\n\nThe team-fit call got scheduled, then pushed. Rescheduled, then pushed again. After the second deferral it was quietly cancelled, and not long after I got the formal rejection. The technical signal was strong, but the Googlyness concern from that one round did not clear the bar.\n\nThe frustrating part is that I genuinely thought the coding was the hard part. It was not. The hard part was demonstrating, under pressure, that I am someone people want in the room when things go sideways. I treated the behavioral round as a formality and answered like I was reciting a resume.\n\nIf I run it back: collaboration signal is not a checkbox. Three Strong Hires did not save me from one room where I forgot to actually talk like a person.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Junior SWE', interviewStage:'FINAL', rejectionYear:2024, userIndex:1 },
  { communityKey:'google/swe', title:'Overcomplicated a two-pointer problem and ignored the hint', body:`**Company**: Google\n**Position**: SDE-II\n**Stage**: Onsite (Round 1)\n**Self-Analysis**: Reached for memoization on a problem that wanted two pointers, then talked past the interviewer's hint.\n\n---\n\nSDE-II loop. Round 1 was, in retrospect, a clean two-pointer problem. I did not see it that way in the moment. I anchored on a complicated memoization approach and committed to it well past the point where I should have stepped back.\n\nThe interviewer gave me a real hint — gently nudging toward scanning from both ends. I heard it, acknowledged it, and then kept going down my own road because I had already invested in the design.\n\nThat round came back No Hire. Round 2 was an easier problem and I solved it cleanly, which almost made it worse — it proved I could do the work when I was not busy fighting myself.\n\nThe recruiter's summary was blunt and fair: I overcomplicated the solution. Not "you could not solve it," but "you made a simple thing hard and would not let the interviewer help you."\n\nThe lesson: when an interviewer offers a hint, stop, restate what they are pointing at, and pivot. A hint is not a suggestion you can decline. It is the most valuable signal in the room, and I declined it.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'SDE-II', interviewStage:'ONSITE', rejectionYear:2024, userIndex:2 },
  { communityKey:'google/swe', title:'Aced the DSA rounds, then answered ML questions like an engineer instead of a product person', body:`**Company**: Google\n**Position**: ML Engineer\n**Stage**: Onsite (domain round)\n**Self-Analysis**: Strong on algorithms, but gave purely technical answers to product-framed ML questions.\n\n---\n\nML Engineer loop. Three DSA rounds, one ML domain round, one Googlyness round. The three algorithm rounds went well. I walked into the ML domain round feeling like the hard part was behind me.\n\nIt was not. The interviewer kept reframing things toward the product: "How do you know the model is good enough?" "What does the user actually experience when the model is wrong?" I answered every one with metrics — precision, recall, calibration curves, offline eval. All correct. All beside the point.\n\nWhat they wanted: connect the model to a person on the other end. I kept retreating into the technical layer because that is where I am comfortable, and the feedback reflected that — strong fundamentals, no product judgment.\n\nThe recruiter was constructive. She told me the gap was coachable and encouraged me to reapply after six months.\n\nSitting with it: "is the model good enough" is never a metrics question in an ML product role. It is a question about acceptable failure for a real user. I answered the math and missed the human.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'ML Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:3 },
  { communityKey:'google/swe', title:'No working code on the graph round, and communication flagged in Googlyness', body:`**Company**: Google\n**Position**: Software Engineer\n**Stage**: Onsite (4 rounds)\n**Self-Analysis**: Failed to produce working code on one round; communication friction compounded it.\n\n---\n\nFour onsite rounds for a Software Engineer role. The round that ended it was a graph exploration problem. I understood the shape of the solution but I never got to working code. I had pseudocode, a plan, hand-waving where the implementation should have been.\n\nThe Googlyness round added a second problem. English is not my first language, and under time pressure my explanations got tangled. The interviewer noted communication as a concern — not the content of what I was saying, but how hard it was to follow.\n\nThe recruiter's parting line: "Communication is key." I initially read that as soft feedback. The longer I sat with it, the more I understood it was the actual diagnosis. On the graph round, if I had narrated my plan clearly, the interviewer could have helped me get to running code.\n\nThe analytical takeaway: communication is the channel through which your technical signal reaches the interviewer. If that channel is noisy, even correct thinking reads as weak.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:4 },
  { communityKey:'google/swe', title:'Got the personalized "you passed our screen" email — then rejected on an eligibility rule', body:`**Company**: Google\n**Position**: Software Engineering Intern\n**Stage**: Resume Screen\n**Self-Analysis**: Cleared the ATS and a human screen, lost to an enrollment requirement I did not meet.\n\n---\n\nI applied for a SWE internship as an undergrad. My resume cleared the ATS — I know because I got an actual personalized email with a real person's name and specific references to my background. For about a day I let myself believe I had broken through the part everyone says is hardest.\n\nThen the rejection. Not for fit, not for skills. For eligibility. The role required candidates to be in their penultimate or final year, and I was not far enough along.\n\nThe whiplash of "a real human liked your profile" followed immediately by "but a timeline rule disqualifies you" is a specific kind of frustrating. It is not a no about me. It is a no about when.\n\nThe frame I have settled on: not yet, not this role, not this timeline. That is three different things and none of them is "not good enough." Rejection is data, not destiny.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineering Intern', interviewStage:'SCREEN', rejectionYear:2024, userIndex:5 },

  // ── AMAZON ──
  { communityKey:'amazon/swe', title:'Passed every round I could see, rejected with no reason five days later', body:`**Company**: Amazon\n**Position**: Senior SWE\n**Stage**: Onsite (5 rounds)\n**Self-Analysis**: Strong technicals; likely thin Leadership Principles stories with weak metrics.\n\n---\n\nSenior SWE process. Cleared the OA, cleared the phone interview, cleared all five onsite rounds. From inside each room, every one of them felt like a pass.\n\nFive days later the rejection arrived with no stated reason.\n\nMy best reconstruction: the LP stories. The coding and design were not the gap. But when I replay my behavioral answers, they were narrative without numbers — I described what I did and why it mattered, but I rarely quantified the impact. No "reduced X by Y percent," no scale, no measurable outcome. At this level the bar raisers are listening for metrics, and I gave them stories.\n\nWhat I am changing: every LP story gets a number now. Situation, action, and a quantified result. I had the substance and told it like a memoir instead of a metrics review. At senior level, the absence of numbers reads as the absence of impact, even when the impact was real.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior SWE', interviewStage:'ONSITE', rejectionYear:2024, userIndex:6 },
  { communityKey:'amazon/swe', title:'Told my system design was weak — the one round I thought I crushed', body:`**Company**: Amazon\n**Position**: SDE-2\n**Stage**: Onsite\n**Self-Analysis**: My self-assessment and the actual feedback pointed in opposite directions.\n\n---\n\nSDE-2 loop. The behavioral rounds hit the LP hard. The technical portion included a system design round that I walked out of feeling great about. I thought I had partitioned the problem cleanly, reasoned about scale, handled the obvious bottlenecks. If you had asked me to rank my rounds, system design was the top.\n\nThe feedback said system design was my weakest area.\n\nThat reversal is the part I still cannot fully metabolize. It means my internal gauge for "did that go well" is calibrated wrong, which is scarier than a knowledge gap because I cannot feel where the edges are.\n\nMy reconstruction: I optimized for breadth — touched many components and sounded fluent — when the interviewer wanted depth on the hard tradeoffs. Fluency felt like strength to me and read as hand-waving to them.\n\nThe uncomfortable lesson: "that felt great" is a flag to interrogate, not a result to trust.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'SDE-2', interviewStage:'ONSITE', rejectionYear:2024, userIndex:7 },
  { communityKey:'amazon/swe', title:'Knew every single problem and still went completely blank on implementation', body:`**Company**: Amazon\n**Position**: SDE-2\n**Stage**: Onsite\n**Self-Analysis**: Recognized every problem; could not implement any of them under pressure.\n\n---\n\nSDE-2 loop in Seattle. I had seen every problem they gave me. The array partition variant, the meeting-room scheduling question — these were not surprises. I recognized each one the moment it was on the board.\n\nAnd then, at the implementation step, I went blank. Repeatedly. Recognition did not convert into working code.\n\nThe lesson is one I thought I already knew: understanding beats memorization, and I had been training the wrong one. I had memorized the existence of solutions without ever rehearsing the muscle of writing them from scratch under a clock. Knowing the answer exists is worthless if your hands cannot build it while someone watches.\n\nI am back to implementing from empty files, no templates, timer running.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'SDE-2', interviewStage:'ONSITE', rejectionYear:2024, userIndex:8 },
  { communityKey:'amazon/swe', title:'Three rounds, every interviewer seemed satisfied, and I still believed I had it', body:`**Company**: Amazon\n**Position**: New Grad SDE\n**Stage**: Onsite (3 rounds)\n**Self-Analysis**: Felt strong across all rounds; the rejection still landed.\n\n---\n\nNew grad loop. Round one was LP behavioral. Round two was system design — design a URL shortener — which I had prepped and felt good about. Round three was LP and coding.\n\nThe thing I keep coming back to is the interviewers' faces. They seemed satisfied. I let myself believe, fully, that I had it. Not hoped — believed.\n\nThe rejection email came in July. The analytical part of me knows: I cannot actually see my own signal. Satisfied-looking interviewers are not a scorecard. Engagement is not endorsement. Somewhere across those three rounds there was a gap a bar raiser saw and I did not.\n\nWhat I am keeping: the feeling of "I had it" is not information. It is hope wearing information's clothes.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'New Grad SDE', interviewStage:'ONSITE', rejectionYear:2024, userIndex:9 },
  { communityKey:'amazon/swe', title:'"Moving forward with other candidates" — recycled, not rejected', body:`**Company**: Amazon\n**Position**: SDE-2\n**Stage**: Onsite (full loop)\n**Self-Analysis**: Full loop passed the bar but lost the seat.\n\n---\n\nFull loop. "Moving forward with other candidates." No reasons, no scores.\n\nThe recruiter's follow-up: they wanted to connect me with other teams — this was not a "you failed" but a "we will find you a different home." For a few weeks I held onto that.\n\nThen the other-team conversations quietly evaporated, and what had been framed as a transfer became, in effect, a hard reject.\n\nSomeone left a comment that reframed it for me: "You were recycled, not rejected." That distinction matters. It means the bar raisers signed off on me as hire-able; what I lost was a seat, not a verdict on my competence. The loop said yes to the engineer and the org said no to the timing.\n\nThe dry version: "recycled" still ends in no offer. But it changes what I take into the next loop. I am not re-proving I can pass. I am hunting for a team with an open seat the day my loop closes.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'SDE-2', interviewStage:'ONSITE', rejectionYear:2024, userIndex:10 },

  // ── META ──
  { communityKey:'meta/swe', title:'Both coding rounds came back No Hire — and I genuinely thought one was a slam dunk', body:`**Company**: Meta\n**Position**: Senior Software Engineer\n**Stage**: Full Loop — London\n**Self-Analysis**: My read of my own performance was wrong by a full grade.\n\n---\n\nLondon loop. Two coding rounds, one system design, one behavioral. The first coding round I never landed the optimal solution — I knew it walking out. But the second one I solved cleanly, handled the follow-up, tested edge cases. I left that room genuinely upbeat. System design felt strong. Behavioral was easy.\n\nThen the recruiter call: "Both coding rounds came back as No Hire." Both. I asked her to repeat it.\n\nThe second round — the one I was proud of — was scored a No Hire, and she could not give me specifics beyond "the bar for signal at this level is high."\n\nThat discrepancy is the part that still messes with me. If my own sense of a "good" round is that miscalibrated, I do not actually know what I am being measured on. I have stopped trusting the feeling of a good interview and started recording myself solving problems out loud, because the gap between "felt great" and "scored No Hire" is the only thing worth fixing.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:11 },
  { communityKey:'meta/swe', title:'Crushed the middle of the loop, then the surprise supplemental round buried me', body:`**Company**: Meta\n**Position**: Software Engineer, Mid-Level\n**Stage**: Onsite Loop (5 rounds)\n**Self-Analysis**: I peaked in the middle and gassed out at the end.\n\n---\n\nFive rounds in a single day. Coding 1: Tree BFS variant, did not nail the optimal space complexity. Behavioral: good rapport. System design: post-search style problem, genuinely collaborative. Coding 2: Tree BFS again, got both optimal. Momentum felt great.\n\nThen a supplemental round at the end — a hard palindrome partitioning problem plus Grid DFS, and under the fatigue of round five I froze and never recovered. I knew in real time that I had torched it.\n\nRejection came the same day.\n\nThe structure of the day matters more than any single problem. I spent my best energy on the system design I was already going to pass and had nothing left for the supplemental that actually decided the outcome. For the next loop I am doing full five-problem mock days back to back, because solving one hard problem fresh proves nothing about solving the fifth one exhausted.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer, Mid-Level', interviewStage:'ONSITE', rejectionYear:2024, userIndex:12 },
  { communityKey:'meta/swe', title:'My coding was fine. The behavioral rapid-fire is what actually sank me', body:`**Company**: Meta\n**Position**: Senior Engineer\n**Stage**: Full Loop\n**Self-Analysis**: I treated behavioral as the easy round. At senior level it is a gauntlet.\n\n---\n\nMy coding rounds went well — no complaints there. The behavioral is what ended me.\n\nIt opened with my strongest story, the one I had polished for years. The interviewer cut in almost immediately: "Do you have something more recent?" Then it turned into rapid-fire: tough coworker, difficult manager, time you disagreed with a decision, time you delivered bad news. Question after question, barely a beat between them.\n\nI ran out of polished material around the third prompt and started improvising — narrating generic principles instead of concrete situations, which at Meta is the exact failure mode.\n\nRejection followed. The lesson is brutal in its simplicity: I prepared a handful of greatest-hits stories and the format demanded a deep bench of recent ones. For the next loop I am building a matrix — conflict, failure, leadership, ambiguity — with at least three recent examples per category, all rehearsed in STAR format.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:13 },

  // ── APPLE ──
  { communityKey:'apple/swe', title:'Passed all six rounds, talked comp, then they selected another candidate — and reposted the role next day', body:`**Company**: Apple\n**Position**: Senior Software Engineer\n**Stage**: Final / Comp Discussion\n**Self-Analysis**: The rejection reason and the timeline did not line up.\n\n---\n\nSix rounds, all passed. The HR call to talk compensation went normally. I gave my expectation; she said she needed to confirm the level internally.\n\nA week later: "We have decided to move forward with another candidate." The next day the exact same role was reposted.\n\nMy honest read: my comp expectation, paired with a level that may not have been locked in, created friction somewhere I never had visibility into. Maybe the band did not fit the budget; maybe there was an internal candidate the whole time. I will never know.\n\nLesson: get the level and band pinned down explicitly before you state a hard number. The interviews were never my problem. The parts I could not see were.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer', interviewStage:'FINAL', rejectionYear:2024, userIndex:14 },
  { communityKey:'apple/swe', title:'"Technically fine, fit unconvincing" — I aced the engineering and whiffed the team-interest question', body:`**Company**: Apple\n**Position**: Senior Software Engineer (Platform Engineering)\n**Stage**: Onsite — Cupertino\n**Self-Analysis**: I optimized 100% for technical signal and 0% for demonstrating genuine, specific interest in the team.\n\n---\n\nCupertino onsite for a platform engineering team. Phone screen OOP was clean. Onsite: memory management deep-dive, Swift concurrency reasoning, debugging exercise — technically solid in every room.\n\nThen the hiring manager round. He asked, in different ways, why this team, why this domain. And I gave him air: "I love performance work." "I really respect Apple's engineering bar." Generic, interchangeable answers I could have given to any team at any company. He could tell, and I could tell he could tell.\n\nRejection summary: "technically fine, fit unconvincing." Exactly right.\n\nLesson: at Apple, passing every algorithm round buys you nothing if you cannot articulate specifically why you want to be on that team solving those problems. Before the next onsite I am researching the actual team — their talks, their releases, their public problems.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:0 },

  // ── STRIPE ──
  { communityKey:'stripe/swe', title:'Solved the problem and one follow-up — at Stripe that is not enough', body:`**Company**: Stripe\n**Position**: Backend Engineer (Remote, India)\n**Stage**: Screening Round\n**Self-Analysis**: Correct does not equal fast enough. Stripe grades solve-plus-multiple-follow-ups.\n\n---\n\nHM call first, then the screening round: an API response parser problem with the expectation that follow-ups would extend it. I got the core implementation working and made it through the first follow-up cleanly. Then I ran out of time mid-way through the second.\n\nA week later, rejection. The throughline was speed: "The standard is to solve the base problem and get through two to three follow-ups in the given time." I had treated the base solution as the goal and the follow-ups as bonus. Their model is the opposite.\n\nStripe's format rewards velocity and extensibility together. My code was correct and readable. It just was not fast, and at Stripe correct-but-slow reads the same as incomplete.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Backend Engineer', interviewStage:'SCREEN', rejectionYear:2024, userIndex:1 },
  { communityKey:'stripe/swe', title:'New grad, solved 2 of 3 in time — and at Stripe 2 of 3 is a reject', body:`**Company**: Stripe\n**Position**: Software Engineer, New Grad (India)\n**Stage**: Coding Assessment\n**Self-Analysis**: Two-thirds done is a clean, complete failure under their rubric.\n\n---\n\nNew grad, and I had heard Stripe interviews were multi-part but underestimated what that meant for pacing. Three connected problems, implicit bar is all three solved within the time. I finished the first two solidly. The third I started but could not land before time ran out.\n\nThe rejection was direct: I could not complete 3 of 3 in the window. And 2 of 3 is not a partial pass — it is a reject.\n\nStripe's format demands speed AND extensibility simultaneously. Each part builds on the last, so you must architect the early parts cleanly enough that extending them later is fast, and you must move quickly enough to reach the later parts at all.\n\nI spent too long polishing parts one and two and starved part three of time. For the retry I am practicing multi-part problems specifically, optimizing for "leave yourself room for the next part" rather than "make this part perfect."\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer, New Grad', interviewStage:'SCREEN', rejectionYear:2024, userIndex:2 },
  { communityKey:'stripe/swe', title:'Made it to the Bug Squash round and got lost in a huge unfamiliar codebase', body:`**Company**: Stripe\n**Position**: Software Engineer, New Grad\n**Stage**: Onsite Loop\n**Self-Analysis**: My algorithm prep was solid; my "debug a large real codebase under pressure" muscle was weak.\n\n---\n\nNew grad onsite. Phone screen was a four-part problem and I solved all four. Onsite opened with an advanced programming round, two parts, both handled fine. Then came the Bug Squash round: a large, unfamiliar Java/Kotlin codebase, a reported bug, and a stopwatch.\n\nJust orienting — finding where the relevant logic lived, understanding the call paths — ate most of my time. I was navigating, not debugging. The interviewer eventually gave me hints that pointed me toward the right area, and I did find the bug, but the performance was clearly weak. The manager round afterward went well, but it could not rescue the Bug Squash result.\n\nRejection came a few days later. The lesson: Stripe's Bug Squash tests fast comprehension of a large existing codebase and methodical fault isolation, not algorithm design from a blank file. For the next attempt I am practicing on real open-source repos: clone something large, find a logged bug, and time myself locating and fixing it.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer, New Grad', interviewStage:'ONSITE', rejectionYear:2025, userIndex:3 },

  // ── NETFLIX ──
  { communityKey:'netflix/swe', title:'Five months in, no return offer — did not meet the bar for a mid-level engineer', body:`**Company**: Netflix\n**Position**: Software Engineer (Short-Term Role)\n**Stage**: End-of-Term Review\n**Self-Analysis**: Netflix holds early-career people to a mid-level bar. I met junior good and the bar was mid-level good.\n\n---\n\nFive months in a short-term role. When the conversion conversation came, the answer was no: I had not met Netflix's expectations for a mid-level engineer. Not "you were bad." Just: the bar here, even for someone early in their career, is mid-level, and I landed under it.\n\nMy first reaction was that the five months had been a waste. But the more I unpacked it, the less true it felt. Netflix's culture compresses the timeline — there is no junior tier to grow into slowly, so they evaluate you against autonomy, judgment, and impact from day one. I got dropped into ambiguous problems with minimal hand-holding. I did not fully clear it — but I spent five months stretching toward it.\n\nLesson for anyone heading into a Netflix-style environment: go in expecting to be measured against mid-level autonomy from the start, and treat the term as the education even if the offer does not come.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'FINAL', rejectionYear:2024, userIndex:4 },
  { communityKey:'netflix/swe', title:'Rejected from a senior IC role because I have managed before', body:`**Company**: Netflix\n**Position**: Senior Software Engineer (Individual Contributor)\n**Stage**: Final / Hiring Manager Decision\n**Self-Analysis**: I was screened out for fit on the basis of past management experience — for an IC role.\n\n---\n\nI applied for a senior IC position. I have real engineering depth and I also happen to have spent time managing a team. The loop went well technically. The rejection came down to "team fit" — the substance was that my prior management experience made the hiring manager doubt I would be content as a pure IC.\n\nLet me be precise about why this bothers me: I applied for an IC role, I want an IC role. Treating "this person has led before" as a reason to doubt their fit for an IC seat inverts the logic. Leadership experience makes someone a better senior IC, not a worse one. Framing that as a disqualifier creates an artificial barrier.\n\nThe Netflix-specific edge: the rationale leaned on a misread of their freedom-and-responsibility culture — as if my management background was a red flag, when it was really just a culture-mismatch judgment dressed up as feedback.\n\nDry takeaway: if you have managed and are going back to IC, address it head-on before the hiring manager invents the objection for you.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer (IC)', interviewStage:'FINAL', rejectionYear:2024, userIndex:5 },

  // ── MICROSOFT ──
  { communityKey:'microsoft/swe', title:'Passed every round at Microsoft, then the AA round buried me on system design', body:`**Company**: Microsoft\n**Position**: Software Engineer\n**Stage**: Onsite (As-Appropriate / final loop)\n**Self-Analysis**: Strong on coding and OOP design but never invested in system design depth.\n\n---\n\nThree interviews at the European office: OOP design, a system design discussion, two coding rounds on medium-difficulty problems. I cleared all of them — the feedback in the moment was warm.\n\nThen came the AA round, the final loop where a more senior interviewer pressure-tests you. The whole thing collapsed on system design. I could describe the high-level architecture fine, but the moment they pushed — how does your cache invalidation behave under a partition? what happens to in-flight writes when a node dies? — I was hand-waving. I knew the vocabulary. I did not know the mechanics.\n\nThe rejection was almost gentle, which made it worse. Every earlier round had been a green light, and the one round that mattered most exposed the exact thing I had been avoiding.\n\nLesson: system design depth is not a vibe. It is drilling failure modes, capacity math, and tradeoffs until you can go five whys deep without flinching.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:6 },
  { communityKey:'microsoft/swe', title:'Got an informal offer at Microsoft Redmond, then a rejection — half the loop felt hostile', body:`**Company**: Microsoft\n**Position**: Software Engineer (Redmond)\n**Stage**: Final\n**Self-Analysis**: I learned to treat every single touchpoint as evaluative, because the one I dismissed as casual was the one that counted.\n\n---\n\nI passed all four final interviews. I received what was, in plain words, an informal offer — a recruiter walked me through comp ranges. I started telling people. And then: rejected.\n\nWhat still gets me is the "intro call" early on. It was framed as a get-to-know-you, low stakes, just vibes. It was not. It was an actual interview, and I treated it like a coffee chat.\n\nThe loop itself was uneven. Roughly half the interviewers were collaborative and sharp. The other half seemed checked out. One opened with a brain-teaser riddle, then asked me to write code in the Teams chat window — no editor, no syntax help.\n\nI am angry. Not because I got rejected, but because an informal offer was dangled and then yanked, and because the experience was so inconsistent.\n\nThe one thing I will carry: there is no such thing as an intro call. Everything is the interview.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'FINAL', rejectionYear:2024, userIndex:7 },
  { communityKey:'microsoft/swe', title:'Three great onsite rounds at Microsoft, one botched data structure — and that was enough to reject me', body:`**Company**: Microsoft\n**Position**: Software Engineer II\n**Stage**: Onsite\n**Self-Analysis**: Let one data structure implementation I had not drilled recently sink an otherwise strong loop.\n\n---\n\nPhone screen went smoothly, so I walked into the onsite feeling prepared. Four rounds.\n\nRound 1 was the disaster: implement a binary search tree from scratch — insertion, traversal, the works. I froze on the balancing logic and the interviewer ended up feeding me hint after hint. I limped to something working but it was ugly and slow.\n\nThen, oddly, everything else went well. Round 2 was OOP and SOLID principles, capped with designing a chess board model — I was in my element. Round 3 was system design for a marketing campaign platform. Round 4 behavioral connected.\n\nThree strong rounds. One weak one. Rejected.\n\nThe loop is not averaged. A single round where you visibly struggle on fundamentals can outweigh three where you shine. The BST was not even conceptually hard — I just had not hand-written one in months and assumed I would improvise it. Bad assumption.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer II', interviewStage:'ONSITE', rejectionYear:2024, userIndex:8 },
  { communityKey:'microsoft/swe', title:'I solved the coding problem at Microsoft but could not explain my own past project', body:`**Company**: Microsoft\n**Position**: Software Engineer\n**Stage**: Onsite\n**Self-Analysis**: I could write the code but I could not talk about my own work.\n\n---\n\nThe non-technical round went fine. It was the technical round that exposed me.\n\nThe interviewer asked me to walk through a batch processing system I had built. I had designed it, shipped it, it was running in production. And I could not explain it. I kept drifting into vague summaries — "it processes the jobs and handles retries" — and the interviewer kept pulling me back: "Technical details. Technical details."\n\nThe ironic part: the actual coding problem — find the smallest missing positive number — I eventually solved. The algorithm went better than the project discussion.\n\nDidn't matter. The overall impression was that I could not communicate technically about work I had literally done myself.\n\nLesson: document your work as you do it, and practice explaining past projects out loud — the decisions, the tradeoffs, why you chose X over Y. Building the thing is only half. Being able to defend it under interrogation is the other half.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:9 },

  // ── AIRBNB ──
  { communityKey:'airbnb/swe', title:'Airbnb told me I did well, then went with someone else — the rounds were a black box', body:`**Company**: Airbnb\n**Position**: Software Engineer\n**Stage**: Onsite\n**Self-Analysis**: My instincts on the problems were fine, but I lost time on ambiguity I could not resolve.\n\n---\n\nThe Code Review round was the most uncomfortable: the interviewer barely spoke. I would talk through a change, ask whether they wanted me to go deeper, and get near silence.\n\nBoth coding rounds had genuinely ambiguous prompts, and clarification was like pulling teeth. In one, I committed to an approach, got maybe 75% of the way through a working implementation, and only then did the interviewer mention the approach was wrong for what they wanted. That late redirect cost me almost all my remaining time.\n\nA week later: "You did well, but we decided to go with a different candidate."\n\nWhat I am taking from it: when interviewers will not give signal, you have to manufacture it yourself. State your assumptions out loud and lock them in early — "I am going to assume X and optimize for Y, stop me if that is wrong" — so a silent interviewer is forced to correct course before you have burned 75% of the clock on the wrong path.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:10 },
  { communityKey:'airbnb/swe', title:'Passed Airbnb coding and system design — sunk by a behavioral round I still disagree with', body:`**Company**: Airbnb\n**Position**: Senior Software Engineer\n**Stage**: Onsite\n**Self-Analysis**: Technically I cleared the bar. The hiring manager read my storytelling as ego and lack of humility.\n\n---\n\nCoding round was good, and System Design I passed cleanly.\n\nThe Code Review round had a structural trap. Three PRs under time pressure. I worked through the first two carefully and ran out of clock before the last, biggest one — which, I suspect, was the most important.\n\nThe Engineering Experience behavioral round is what actually ended it. I described a cross-platform migration project, including friction with collaborators. The hiring manager's feedback: no accountability, no humility, spoke poorly of coworkers. I genuinely do not agree with that read — I thought I was being candid. But the perception became the verdict.\n\nIn senior behavioral rounds, you are not just asked what happened — you are evaluated on how you frame other people when things went wrong. Even accurate criticism of coworkers reads as a red flag. Own your share first, frame others charitably.\n\nRejected on the soft skills, after passing the hard ones.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:11 },

  // ── SHOPIFY ──
  { communityKey:'shopify/swe', title:'Shopify does not grade LeetCode — they grade whether your code is production-ready', body:`**Company**: Shopify\n**Position**: Software Engineer (Toronto)\n**Stage**: Onsite\n**Self-Analysis**: I prepped for an algorithms gauntlet and walked into a code-quality evaluation.\n\n---\n\nThe recruiter set expectations correctly: "It is not LeetCode, and we are not grading time complexity." I built a working solution. But I structured it badly under time pressure — nested classes tangled together, naming I would never ship. It ran, it produced correct output, and I was reasonably happy with it.\n\nRight before the interviewer wrapped up, they asked: "Is this production-ready code?" I gave a hand-wavy "well, with some cleanup..." answer.\n\nA few days later: rejection.\n\nThe lesson is specific to how Shopify evaluates: correctness is table stakes. They are watching whether you write code a teammate could maintain — clean structure, sensible decomposition, naming — while solving the problem. "Is this production-ready?" was the actual rubric, voiced out loud, and I answered it the wrong way by having written rough code in the first place.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:12 },
  { communityKey:'shopify/swe', title:'Crushed Shopify coding challenge, finished 20 minutes early — and got cut at screening anyway', body:`**Company**: Shopify\n**Position**: Senior Software Engineer (remote)\n**Stage**: Screen\n**Self-Analysis**: I can not self-diagnose this one, and that is what stings.\n\n---\n\nRemote screening round. The coding challenge went great — I finished twenty minutes early with a clean, correct solution. The conversation was easy and genuine. I walked away as confident as I have ever been after a screen.\n\nThen the rejection email landed.\n\nIt makes no sense to me to cut someone at the screening stage when they are visibly crushing the assignment. If I had bombed it I would understand. But to nail a screen and still get cut before the real loop? I am left with nothing to fix.\n\nMaybe it was fit. Maybe headcount. Maybe a stronger candidate filled the slot the same day. I will never know, and the not-knowing is the actual pain here, more than the rejection itself.\n\nThe only lesson I can extract: sometimes you do everything right and it still ends, and you have to be okay closing that tab without an answer.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer', interviewStage:'SCREEN', rejectionYear:2024, userIndex:13 },
  { communityKey:'shopify/swe', title:'Shopify called it a real-world implementation problem — it was DSA and I was not ready', body:`**Company**: Shopify\n**Position**: Software Engineer\n**Stage**: Onsite\n**Self-Analysis**: I prepared for the format I was told about, not the format I got.\n\n---\n\nThe framing set my entire prep strategy, and the framing was misleading. I was told to expect a "real-world implementation problem" — practical, build-a-feature. So that is what I prepped for. I deliberately deprioritized algorithm drilling because, I reasoned, that is not what this round was about.\n\nThen the round started and it was, functionally, a DSA-style coding challenge. Algorithmic thinking, the kind of pattern-matching you only have sharp if you have been drilling it recently. And I had not.\n\nRejected, and fairly — I was not prepared for what actually showed up.\n\nThe lesson: research the company-specific format before every interview, and do not take the recruiter one-line description as gospel. "Practical" and "real-world" mean wildly different things at different companies. Prep for the worst-case format, not the comfortable one you were promised.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:14 },

  // ── FIGMA ──
  { communityKey:'figma/swe', title:'Two months and 8 hours of interviews at Figma — rejected on coding after three strong rounds', body:`**Company**: Figma\n**Position**: Software Engineer (London)\n**Stage**: Onsite\n**Self-Analysis**: Three coding-adjacent rounds felt strong, the feedback was "coding not strong enough," and the process was so long that the verdict felt almost arbitrary.\n\n---\n\nRoughly two months across about eight contact hours — one of the least efficient processes I have experienced. Two filtering rounds up front, then a five-hour virtual panel: architecture round, EM chat, technical deep dive, two coding rounds.\n\nThree of those were meaningfully about coding, and I felt good about all of them. No moment where I thought "that is the one that sank me."\n\nThe operational side was rough. One interviewer simply no-showed, which threw off the schedule.\n\nThen the rejection: "coding not strong enough." After three rounds I would have called strong.\n\nThe honest lesson: at high-bar companies, "strong enough for you" and "strong enough for them" can be a wide gap, and a long, inefficient process does not owe you a legible reason.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:0 },
  { communityKey:'figma/swe', title:'Fun pair-programming round at Figma — but I did not finish part one', body:`**Company**: Figma\n**Position**: Software Engineer\n**Stage**: Onsite\n**Self-Analysis**: I stumbled and did not complete the first part. Enjoyable as the round was, that is a hard, objective miss.\n\n---\n\nThe pair-programming exercise was genuinely a fun experience. The interviewer was collaborative, the problem was interesting, and it felt much more like working alongside someone than being interrogated.\n\nBut I stumbled, and I did not finish the first part. The exercise was clearly structured: complete the foundational first part, then extend into more advanced territory if time allowed. I got tangled partway through, lost time debugging my own confusion, and never got it cleanly done. I never even reached the extensions.\n\nA pair-programming round is not graded on whether everyone had a nice time. Part one completing is the floor; the extensions are the ceiling. I did not clear the floor.\n\nLesson: in a staged pair-programming exercise, finish part one completely and correctly before reaching for anything fancy. The polished, fully-working foundation beats a half-built ambitious thing every single time.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:1 },

  // ── LINKEDIN ──
  { communityKey:'linkedin/swe', title:'Solved both coding problems in under an hour. Rejected. Then told I needed lots of hints.', body:`**Company**: LinkedIn\n**Position**: Software Engineer (India, remote)\n**Stage**: Coding Round\n**Self-Analysis**: I solved everything cleanly and on time. The feedback I got does not match the interview I lived through.\n\n---\n\nA LinkedIn recruiter reached out to me directly. The coding round had two problems with a one-hour budget. I finished both well inside the hour — clean solutions, walked through complexity, handled the follow-ups. No awkward silences, no getting stuck. I left that call genuinely optimistic.\n\nThen, unexpectedly, a rejection. When I pushed the recruiter for something concrete, the answer was that I "needed a lot of hints" and my "code was not up to standard."\n\nI do not recognize that interview. I was not given hints because I did not need them. The code compiled and ran on the first pass for both problems.\n\nI am not writing this to claim I am flawless. But when the feedback is provably disconnected from what happened in the room, it stops being useful and starts being damaging.\n\nIf a recruiter gives you feedback that does not match reality, write down what actually happened the same day.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'PHONE', rejectionYear:2024, userIndex:2 },
  { communityKey:'linkedin/swe', title:'Ghosted for two weeks after 5 onsite rounds, had to beg a different recruiter for the rejection', body:`**Company**: LinkedIn\n**Position**: Staff Software Engineer\n**Stage**: Onsite (5 rounds completed)\n**Self-Analysis**: I genuinely do not know how I did — they never told me.\n\n---\n\nFive onsite rounds. A full day of my brain wrung out across coding, design, and behavioral. I went home fine about it. Then nothing.\n\nA week passed. I sent a polite check-in. Silence. Another week. Still nothing. Two full weeks of refreshing my inbox after investing an entire interview loop.\n\nWhat finally worked was uncomfortable: I reached out to a different LinkedIn recruiter I had connected with previously and essentially asked them to chase down my own status internally. Only then did an email materialize — a generic rejection, the kind of template you could generate in your sleep.\n\nI am not even upset about the no. Rejections happen. What I cannot get past is that five rounds of someone's time earns you, apparently, less courtesy than an automated ATS bounce.\n\nLesson: get the recruiter's direct contact early and a rough timeline in writing. When the ghosting starts, you will at least know who to escalate to.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Staff Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:3 },
  { communityKey:'linkedin/swe', title:'Infrastructure SWE: passed every round, rejected for "slightly more experience" — felt like a template', body:`**Company**: LinkedIn\n**Position**: Software Engineer, Infrastructure\n**Stage**: HM Round\n**Self-Analysis**: I performed solidly across the board but never gave them a reason to remember me specifically.\n\n---\n\nThe Infrastructure loop was thorough: screening covered a complex project deep-dive, OS fundamentals, and two DSA mediums. Round 2 coding went well. System Design — metric collection pipeline — felt solid. The HM round was friendly.\n\nThen: "We have decided to move forward with a candidate who has slightly more experience."\n\nHere is the part that nagged at me. I compared notes with two other people who interviewed for adjacent roles around the same time, and the wording was word-for-word identical to all of us. "Slightly more experience" to everyone. That is not feedback — that is a mail merge field.\n\nWhat I took from it: passing every round is not the bar. The bar is being the obvious yes. I was competent in all five rounds and unforgettable in none. "Slightly more experience" is what they tell the candidate who was fine.\n\nDifferentiate yourself technically — go one layer deeper than asked on the thing you know best.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer, Infrastructure', interviewStage:'ONSITE', rejectionYear:2024, userIndex:4 },

  // ── UBER ──
  { communityKey:'uber/swe', title:'Backend loop: nailed three coding rounds, then burned my LLD round talking instead of typing', body:`**Company**: Uber\n**Position**: Mid-level Backend Engineer\n**Stage**: Onsite (LLD round)\n**Self-Analysis**: Strong DSA, but I mismanaged the clock on the design round and never shipped working code.\n\n---\n\nThe OA went fine. Round 1 coding was the Candy problem — got to the optimal solution with clean reasoning. Round 2 was a Priority Queue / min-heap problem — optimal again. Three for three on the algorithmic side.\n\nThen came Round 3: Low-Level Design, Parking Lot. We spent a long time on the class diagram. The interviewer kept pulling the discussion deeper, and I kept happily going deeper, because designing is the fun part.\n\nThen I looked up and there were twenty minutes left to actually code. I started implementing and ran out of runway. The session ended with a half-built class skeleton.\n\nRejection followed, and honestly I knew. The discussion was great. The deliverable was not.\n\nLesson: in an LLD round, a beautiful design you did not code is worth less than an okay design that runs. I now hard-cap design talk at the halfway mark and force myself into the editor. Balance the design discussion against actual coding time.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Mid-level Backend Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:5 },
  { communityKey:'uber/swe', title:'Senior SWE: drew a clean Kafka pipeline, rejected for not defending the trade-offs deeply enough', body:`**Company**: Uber\n**Position**: Senior Software Engineer\n**Stage**: Onsite (System Design + LLD)\n**Self-Analysis**: DSA was solid; I lost points on design depth and on raw DSA speed.\n\n---\n\nThe two DSA rounds went fine. System Design was a real-time delivery metrics dashboard. I did what you are taught to do: clarified requirements, scoped read vs write patterns, then designed an ingestion path through Kafka into an aggregation service, with a serving layer for the dashboard. The diagram was clean and the components were all the right ones.\n\nThe problem: I drew the boxes well but defended them shallowly. When the interviewer pushed — why Kafka over a simpler queue here, what is your aggregation window, how do you handle late-arriving events — my answers were surface-level. I named the right tools but could not go three layers deep on why each choice beat the alternatives.\n\nFeedback: rejected on a combination of DSA speed and insufficient depth on system design trade-offs.\n\nAt senior level, the architecture diagram is the easy part. The interview is whether you can defend every single choice against the obvious alternatives. System design is about defending choices, not just drawing boxes.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:6 },

  // ── DATADOG ──
  { communityKey:'datadog/swe', title:'Made it through the full onsite — one interviewer was not satisfied and that was the whole ballgame', body:`**Company**: Datadog\n**Position**: Software Engineer (NY)\n**Stage**: Onsite (4 rounds)\n**Self-Analysis**: One negative vote in a unanimous-style loop is fatal.\n\n---\n\nFour rounds: two technical, one behavioral, one system design. From where I sat, three of them went genuinely well. I left thinking the odds were in my favor.\n\nThen the rejection, and here is the part the recruiter was unusually candid about: they were actually advocating for me internally. But one interviewer was not satisfied, and in their process that single dissent was enough to sink the whole loop. The recruiter said, more or less, "I was fighting for you, but I could not get it past that one room."\n\nThat reframed the whole thing for me. Three enthusiastic yeses do not outvote one firm no.\n\nI do not even know which round it was, which is its own kind of haunting. The takeaway: treat every single round as the one that could end it, because it is. There is no "good enough average" — there is the weakest room you walk into.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:7 },
  { communityKey:'datadog/swe', title:'Behavioral interviewer kept cutting me off. Tech interviewer quizzed a backend hire on frontend JS trivia.', body:`**Company**: Datadog\n**Position**: Senior Software Engineer (NY)\n**Stage**: Onsite\n**Self-Analysis**: The interviewers misread my background, and I did not correct course fast enough.\n\n---\n\nTwo rounds in this loop went sideways, and not because of my answers — because of the framing.\n\nThe behavioral round was with an interviewer who interrupted constantly. Every time I started building out a story about leadership or mentoring, I would get cut off two sentences in with the next question. I never got to land a single complete example.\n\nThe "tech experiences" round was stranger. My background is backend, and the role was backend. But the interviewer spent the time on frontend JavaScript trivia — closures, event-loop minutiae — that had nothing to do with the role.\n\nThe rejection followed, and I genuinely think the interviewers misjudged who they were talking to.\n\nMy regret is that I stayed passive. I should have said clearly: "Just to make sure we use the time well — this is a backend role and my experience is backend; is the frontend focus intentional?" A respectful clarifying question reframes the room. If an interviewer's questions seem off-target for the role, ask to clarify the scope.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:8 },
  { communityKey:'datadog/swe', title:'The CoderPad exercise had two parts. Nobody told me. I solved one and got rejected.', body:`**Company**: Datadog\n**Position**: Senior Software Engineer\n**Stage**: Onsite (CoderPad coding round)\n**Self-Analysis**: I solved what I was given thoroughly. I just did not know there was a second half.\n\n---\n\nThe coding round was a large CoderPad exercise. I dug in, read the prompt carefully, and built out what was in front of me — a complete, working solution to what I understood to be the problem.\n\nWhat the recruiter never told me, and what was not obvious from the prompt, was that the exercise had two distinct parts. I never started the second one.\n\nThe rejection reason: I did not complete the second part. I would gladly have managed my time differently if anyone had said "there are two sections, budget accordingly." The recruiter did not explain the structure correctly.\n\nThis was completely avoidable. It was not a skill gap — it was an information gap.\n\nLesson I will never skip again: before you write a single line, ask how the exercise is structured. "How many parts are there, and how should I split my time?" Ten seconds of asking would have saved this entire loop.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:9 },

  // ── OPENAI ──
  { communityKey:'openai/swe', title:'Every onsite round felt easy. I got rejected anyway and have no idea what I would even fix.', body:`**Company**: OpenAI\n**Position**: Staff Engineer\n**Stage**: Onsite\n**Self-Analysis**: I genuinely cannot identify a weak round, which is somehow worse than knowing.\n\n---\n\nThe onsite felt good. Not nervously-optimistic good — actually good. Every round, I solved what was asked, the conversations flowed, the interviewers seemed engaged, and at no point did I hit a wall. I walked out thinking the rounds were on the easier side relative to what I had prepped for.\n\nThen the rejection landed, and I just stared at it.\n\nWhen everything feels easy and you still get the no, your whole self-assessment model breaks. Was the bar just much higher than the difficulty suggested? Did I misread "smooth" as "strong" when the interviewers were quietly unimpressed by competent-but-not-exceptional answers?\n\nI asked for feedback. I got ghosted on that request.\n\nIf there is a takeaway: "I solved everything and it felt easy" is not the same as "I cleared the bar." Smooth answers can still be unremarkable ones. I am trying to stop treating ease as a signal of strength — and to make peace with the fact that sometimes you do everything right and the answer is still no.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Staff Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:10 },
  { communityKey:'openai/swe', title:'AI companies make you design the systems they actually run — my system design was not ready for that', body:`**Company**: OpenAI\n**Position**: Full-stack Engineer\n**Stage**: Onsite (System Design)\n**Self-Analysis**: Coding was fine; system design — especially AI-adjacent systems at scale — was the gap.\n\n---\n\nGoing in, I knew system design was my soft spot, and the onsite found it immediately.\n\nThe prompt was, essentially, a chat application — streaming responses, session handling, conversation state, scaling the request path. It is not an abstract "design Twitter" exercise; it is uncomfortably close to the real product, which means hand-waving gets caught instantly because the interviewer lives in that system every day.\n\nMy coding rounds were okay. But the design round exposed how thin my preparation was for this specific flavor. As a full-stack engineer, a lot of my system-design study had been generic backend-at-scale material. I had far less practice reasoning about streaming pipelines, token-level latency, and the serving architecture these products depend on.\n\nConcrete advice: study the systems they themselves run. Design a chat app end to end, design a generation/inference serving pipeline. Do not just rehearse generic system design — rehearse their system design.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Full-stack Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:11 },
  { communityKey:'openai/swe', title:'OA was multi-part and I did not finish the second section', body:`**Company**: OpenAI\n**Position**: Software Engineer\n**Stage**: Online Assessment\n**Self-Analysis**: I underestimated the format. The first part was clean; I just ran out of runway before finishing the second.\n\n---\n\nThis one ended before I ever got to talk to a human.\n\nThe Online Assessment was a multi-step coding question. I went deep on the first part — got it working, tested it, felt good about the quality. But the question had a second part that built on the first, and I did not budget enough time for it. I ran out of clock with the second section unfinished.\n\nThe rejection came back tied directly to that: I did not finish the second part.\n\nWhat I got wrong: I treated it like a single-problem sprint where polishing part one was the goal. It was not. It was a multi-part format where completion across all sections is the bar.\n\nLesson: read the entire assessment before you start coding so you know how many parts exist and can pace yourself. Get every section to "working" before you go back and refine any one of them. Completeness beats polish when the rubric is "did you finish all of it."\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'SCREEN', rejectionYear:2024, userIndex:12 },

  // ── COINBASE ──
  { communityKey:'coinbase/swe', title:'New grad backend: ran out of time on the second extension and got cut', body:`**Company**: Coinbase\n**Position**: New Grad Backend Engineer\n**Stage**: Technical Execution Round\n**Self-Analysis**: They grade finished, running code over a good verbal explanation.\n\n---\n\nApplied to a new grad backend role, cleared the CodeSignal OA, got a recruiter call. The Technical Execution interview was machine coding around an order management problem. The setup was an easy base implementation, then a first extension, then a harder second extension stacked on top. I got the base and the first extension working cleanly. Then the clock became the enemy.\n\nI could see the shape of the second extension's solution but did not have minutes left to type and verify it. So I narrated my approach in detail, sketched the data structures, and explained how I would wire it up. The interviewer nodded along.\n\nTwo days later the rejection landed. My honest read: at Coinbase the execution round means execution. A described solution is not a completed one. I think I would have passed if I had cut my explanation short on the first extension and banked time to finish the second in code.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'New Grad Backend Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:13 },
  { communityKey:'coinbase/swe', title:'Thought I nailed the DSA phone screen — the next call never came', body:`**Company**: Coinbase\n**Position**: Software Engineer\n**Stage**: DSA Phone Screen\n**Self-Analysis**: Silent phone-screen rejections are the hardest to diagnose.\n\n---\n\nThis one started almost by accident. I saw a post about openings, applied, and got a CodeSignal OA. Cleared it and got an HR recruiter call. Then the DSA round: a single medium-difficulty question. I worked through it, explained my reasoning out loud, arrived at a correct solution, talked through time complexity. By every signal I could read in the room, it went well.\n\nAnd then nothing. No next call, no scheduling email, no rejection for a while — just silence, which eventually resolved into a no.\n\nThat is the quiet lesson. Onsites you can dissect: a missed edge case, a fumbled design tradeoff. Phone screens with no feedback are the hardest to diagnose, because "correct and clearly explained" can still lose to a candidate who was simply a hair faster or cleaner. You are left optimizing against a verdict you never get to see.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'PHONE', rejectionYear:2024, userIndex:14 },

  // ── BYTEDANCE/TIKTOK ──
  { communityKey:'bytedance/swe', title:'One shallow answer on big data tech and the data infrastructure loop ended that day', body:`**Company**: ByteDance / TikTok\n**Position**: Junior Engineer, Data Infrastructure\n**Stage**: Technical Rounds\n**Self-Analysis**: One shallow answer on a tool I listed can sink an otherwise strong loop.\n\n---\n\nThe OA was a mix of multiple-choice CS fundamentals and two LeetCode-medium coding problems. I cleared it.\n\nRound one was the kind of interview I love. A sliding window problem, then the interviewer layered on additional constraints, then asked me to write unit tests, and finally pushed into scalability — what happens when the input is terabytes. I handled each escalation and walked out confident.\n\nRound two is where it slipped. It opened with implementing an LRU cache, which went fine, and then turned into a tour of big data technologies — S3, Delta Lake, Hive, Spark, Hudi. I could speak to most with real depth. But when the interviewer drilled into Hudi specifically, my answer was thin. I knew the concept at a surface level and it showed.\n\nThe rejection came the same day. In a data infrastructure loop, every technology on your resume is fair game for a depth probe, and one tool you only half-know can outweigh a clean algorithm round.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Junior Engineer, Data Infrastructure', interviewStage:'ONSITE', rejectionYear:2024, userIndex:0 },
  { communityKey:'bytedance/swe', title:'HR said regular technical — it was system design heavy and my LeetCode prep was useless', body:`**Company**: ByteDance / TikTok\n**Position**: Backend Engineer (Singapore)\n**Stage**: Technical Interview\n**Self-Analysis**: Research the actual interview format independently — do not trust the recruiter description.\n\n---\n\nI was up for a backend role, and when HR set up the technical interview they described it as a "regular technical interview." To me that meant the standard thing: a couple of LeetCode-style problems. So that is exactly how I prepped.\n\nThe interview was almost entirely system design. Not a warmup algorithm and then design — design heavy from early on, with deep questions about scaling a service, data partitioning, consistency tradeoffs. My LeetCode preparation was essentially useless in that room.\n\nThe lesson: always research the actual interview format independently of the recruiter's description. A recruiter saying "regular technical" is not a spec. Ask explicitly what each round covers, check recent candidate reports for that exact team and location, and prep to the real bar. Trusting a vague one-liner cost me weeks of prep aimed at the wrong target.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Backend Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:1 },

  // ── PALANTIR ──
  { communityKey:'palantir/swe', title:'New grad: reached task 3 of the Learning round and got "no matching position"', body:`**Company**: Palantir\n**Position**: New Grad Software Engineer\n**Stage**: Learning Interview\n**Self-Analysis**: The Learning round tests adaptability under a moving target, not what you already know.\n\n---\n\nFive-round new grad loop: OA, Karat coding screen, behavioral CTR call, Decomposition interview, and the Learning interview. I cleared everything up to the Learning round, which is where it ended.\n\nThe Learning interview is exactly what it sounds like — they hand you an unfamiliar concept and watch how fast you absorb and build on it. The premise was a plugin manager: declare dependencies, resolve them, load them. It came in escalating tasks, and partway through they added a multithreading requirement. I reached task three but ran out of time before finishing.\n\nThere was no manager final round. The recruiter came back with "we do not have a position matching your skillset," and no actual feedback.\n\nThe Learning round is not testing knowledge — I knew the underlying concepts fine. It is testing adaptability: how quickly you internalize a fresh abstraction and keep extending it as the requirements shift. Reaching task three felt like progress, but throughput on a moving target is the bar.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'New Grad Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:2 },
  { communityKey:'palantir/swe', title:'Onsite day: passed the coding but did not flesh out the answer enough', body:`**Company**: Palantir\n**Position**: Software Engineer\n**Stage**: Onsite Day\n**Self-Analysis**: They want thorough explanations and explored tradeoffs, not just code that works.\n\n---\n\nThe onsite day was three interviews: a system design pairing session, a bug-finding round, and a behavioral "why Palantir" conversation. I had already passed the OA and a LeetCode-medium coding interview to get here.\n\nThe coding-adjacent work went fine on the surface. I got to a working solution, and when prompted I optimized it twice, tightening the complexity each time. By the standard I was used to — does it run, is it efficient — I had cleared the bar.\n\nThat standard was wrong for this company. The feedback was that I "did not flesh out the answer enough." I treated arriving at an optimized solution as the finish line, when here it was closer to the starting point. They wanted me to keep going: enumerate alternatives I rejected and why, discuss tradeoffs, talk through failure modes.\n\nThis place wants thorough explanations, not just working code. A correct, optimized solution delivered tersely reads as shallow to them. Next time I would assume "it works and it is optimal" is the prompt for a deeper discussion, not the end of one.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:3 },

  // ── GITHUB (Atlassian analog) ──
  { communityKey:'github/swe', title:'Six rounds, six Hire ratings — the hiring committee said no anyway', body:`**Company**: GitHub\n**Position**: SDE-2\n**Stage**: Hiring Committee\n**Self-Analysis**: Strong per-round signals can still be overridden by a committee you never meet.\n\n---\n\nSDE-2 role, six rounds. I want to list the verdicts because that is the whole story.\n\nKarat screen: hire. Round one, a code design problem implementing a Snake game with clean architecture: strong hire. Round two, classic DSA: strong hire. Round three, system design: hire. Round four, behavioral: hire. Round five, values-focused interview: hire. Six rounds, six positive ratings, two of them strong. By any individual interviewer's read, I was in.\n\nThen the hiring committee reviewed the package and rejected me.\n\nI have turned this over endlessly. All six interviewers who actually watched me code and reason said yes. A committee that synthesized the written feedback — and presumably weighed me against other candidates, headcount, level calibration, and factors I will never see — said no.\n\nThe lesson is humbling: strong per-round signals do not guarantee an offer. The committee is a separate gate, and against a strong batch or tight headcount, six hires can still net a rejection. You can run the table on the interviews you can see and lose at the table you cannot.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'SDE-2', interviewStage:'FINAL', rejectionYear:2024, userIndex:4 },
  { communityKey:'github/swe', title:'Did really well on the Karat redo — they judged me on the first one anyway', body:`**Company**: GitHub\n**Position**: Software Engineer\n**Stage**: Karat Redo\n**Self-Analysis**: A redo policy may not actually override the first impression — so why offer it?\n\n---\n\nAfter my first Karat coding interview, I was offered a redo. I took it, prepared hard, and genuinely did really well the second time. Clean solutions, good communication, the kind of round you walk away from feeling solid about.\n\nThen they decided not to move me forward, and the reason given was the first Karat interview. The redo, where I had clearly performed better, did not seem to count for much.\n\nThis is the part I cannot square. If the first interview is going to be the deciding signal regardless, why offer the redo option at all? It set an expectation — take it again, do better, get a fair shot — that did not match how the decision was actually made.\n\nLesson: redo policies may not override the first impression. A second chance on paper is not always a second chance in the decision. If you are offered one, do not assume it resets the slate. I treated the redo as my real evaluation when it may have only ever been a formality.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'SCREEN', rejectionYear:2024, userIndex:5 },

  // ── DOORDASH ──
  { communityKey:'doordash/swe', title:'System design interview where the interviewer ate lunch the entire time', body:`**Company**: DoorDash\n**Position**: Software Engineer\n**Stage**: Onsite (System Design)\n**Self-Analysis**: Unprofessional interview environments signal company culture.\n\n---\n\nDoorDash SF, standard SWE loop — two coding rounds and one system design. The coding rounds were fine, nothing remarkable. Then came system design, and within the first minute the interviewer told me he was "going to grab lunch real quick" and never put it down.\n\nI spent forty-five minutes designing a distributed system while listening to someone chew. He would nod between bites, occasionally mumble a follow-up with his mouth full, then go quiet again. At one point I genuinely lost my train of thought.\n\nI kept going because what else are you going to do — call it out and torch the loop?\n\nThe rejection came a few days later. I am not even mad about not getting it. What stuck with me is that this is apparently normal there. If a senior engineer thinks it is fine to eat through a system design round, that tells you exactly how much they value other people's time once you are inside. The interview is the best behavior a company will ever show you. This was the best behavior.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:6 },
  { communityKey:'doordash/swe', title:'Recruiter called it after the system design round and canceled my remaining interviews', body:`**Company**: DoorDash\n**Position**: SDE (Backend)\n**Stage**: Onsite\n**Self-Analysis**: Lost the room early on schema details and never recovered the interviewer's confidence.\n\n---\n\nDoorDash India, backend SDE, five-round loop. It unraveled in the middle.\n\nThe Bug Bash round was in C++ and I had only worked in Python. I flagged it upfront; the interviewer said it was fine. I did okay on the reasoning but the friction of unfamiliar syntax showed.\n\nThen system design: a job scheduler. The interviewer skipped the API discussion — "let us just go straight to design." But the moment I started on the table schema, the interruptions began. Every time I named a column or a relationship, he would jump in to question it before I had finished the thought. I never got to lay out the full picture; the conversation kept fragmenting.\n\nThe round ended awkwardly. Within maybe an hour, the recruiter messaged: not moving forward, and the remaining two rounds were canceled.\n\nLooking back, I should have read the interruptions as a redirect signal and compressed the schema discussion hard instead of trying to be thorough. By the time I adjusted, the verdict was in.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'SDE (Backend)', interviewStage:'ONSITE', rejectionYear:2024, userIndex:7 },

  // ── NOTION ──
  { communityKey:'notion/swe', title:'Six rounds of positive feedback, then a mystery rejection on the final UI exercise', body:`**Company**: Notion\n**Position**: Senior Software Engineer\n**Stage**: Final\n**Self-Analysis**: Positive in-the-room feedback is not a reliable predictor of the final decision.\n\n---\n\nNotion, Senior SWE. Six rounds, and every single one came back positive. I started to let myself believe this one was real.\n\nThe sixth and final round was a TypeScript UI component exercise. The interviewers actively reined me in: "You do not need fancy hooks here, keep it simple." When I went to refactor for robustness: "Honestly it is great as is, do not over-engineer." So I followed their lead, kept it clean and minimal, and we wrapped early with a relaxed Q&A.\n\nThe rejection said my "performance was fine but not strong enough." No elaboration. Fine but not strong enough — on the round where they told me to stop doing more.\n\nWhat I cannot reconcile: I optimized for exactly what they asked for in the moment — simplicity, restraint. Either the in-room guidance was a test I failed by complying, or the real decision was made somewhere in those six positive rounds and the encouragement was just politeness.\n\nStop reading the room as the verdict.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Senior Software Engineer', interviewStage:'FINAL', rejectionYear:2025, userIndex:8 },
  { communityKey:'notion/swe', title:'No Hire after I defended my solution instead of exploring the interviewer hint', body:`**Company**: Notion\n**Position**: Software Engineer\n**Stage**: Onsite\n**Self-Analysis**: When an interviewer suggests an alternative approach, explore it instead of defending your own.\n\n---\n\nNotion SWE, 2025 loop. Three rounds: screening, DSA, and system design.\n\nThe screening was a string-manipulation problem layered on top of a small state-machine. I got through it cleanly.\n\nThe DSA round is where it went sideways. The problem was a tree-navigation question. I had a working approach and was implementing it when the interviewer gently suggested a different angle: "Have you considered approaching it another way?" Instead of genuinely pivoting, I dug in on my own solution, explaining why mine worked. I spent the rest of the round trying to make my version land instead of chasing the hint.\n\nThe system design round — a calendar app — felt solid.\n\nVerdict: No Hire. No feedback.\n\nThe DSA round is what cost me. When an interviewer offers an alternative approach, that is not small talk — it is a lifeline. Defending your solution feels like confidence in the moment but reads as rigidity. The right move was to drop my ego and say "let me try it your way."\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2025, userIndex:9 },

  // ── DATABRICKS ──
  { communityKey:'databricks/swe', title:'New grad loop ended on an OOD/LLD round I had no idea was Amazon-style', body:`**Company**: Databricks\n**Position**: Software Engineer (New Grad)\n**Stage**: Onsite\n**Self-Analysis**: Databricks coding round is OOD/LLD, a distinct prep track from LeetCode.\n\n---\n\nDatabricks New Grad. Phone screen was a clean LeetCode medium. Four-part onsite: algorithm round, cross-functional behavioral, system design, and a final coding round.\n\nThe first three went reasonably. The last coding round caught me completely off guard. It was not another LeetCode-style problem — it was object-oriented design / low-level design. Model this system in classes, define the interfaces, handle the relationships, extend it cleanly when I add requirements. This is essentially Amazon's LLD round, and I had prepped for it the way you would prep for it at Amazon — that is to say, not at all, because nobody told me Databricks does this.\n\nI struggled. I knew the OOP concepts in the abstract but had never drilled the "design this in code under time pressure" muscle.\n\nRejection followed.\n\nThe lesson is purely tactical: Databricks' coding round is OOD/LLD, not pure algorithms. It needs its own distinct prep. If I had known the format existed I would have spent two weeks on it. Instead I walked in optimized for the wrong test.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer (New Grad)', interviewStage:'ONSITE', rejectionYear:2024, userIndex:10 },
  { communityKey:'databricks/swe', title:'Interviewers said I solved every problem correctly, then rejected me to improve technical skills', body:`**Company**: Databricks\n**Position**: Software Engineer\n**Stage**: Onsite\n**Self-Analysis**: Do not conflate interviewer positivity with the actual hire decision.\n\n---\n\nDatabricks, SWE, USA. Two technical phone screens, both passed, then a five-hour virtual onsite.\n\nDuring the onsite, the interviewers were openly encouraging. More than once I heard "yep, that is correct," "nice, that is the optimal solution," "you got it." I walked out of every round believing I had solved the problem they put in front of me, because the people in the room told me so. I left genuinely optimistic.\n\nThen the timeline slipped. They had promised a decision in two weeks; it took four.\n\nThe rejection said I should "improve my technical skills." After interviewers spent five hours telling me my solutions were correct.\n\nThe in-room positivity and the hiring decision are two completely separate processes. Interviewers are nice because being nice keeps the candidate calm and produces better signal — it is not a verdict. The real evaluation is written up afterward, calibrated against other candidates, filtered through a committee you never meet, and it can say the exact opposite of what you heard out loud.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'ONSITE', rejectionYear:2024, userIndex:11 },

  // ── RAMP ──
  { communityKey:'ramp/swe', title:'Coding interview delivered through Gmail while I navigated Calendar live on Zoom', body:`**Company**: Ramp\n**Position**: Software Engineer\n**Stage**: Screen\n**Self-Analysis**: Fintech startups test you in production tools, not CoderPad.\n\n---\n\nRamp SWE, SF, October 2024. The most format-unusual interview I have done.\n\nIt started with a puzzle challenge — a unique-filter task, dedup logic, the sort of thing that screens for whether you can write clean code at all. Passed that, moved to a 1:1 coding interview, and that is where it got weird in an interesting way.\n\nThere was no CoderPad, no shared editor, no LeetCode-style portal. Instead, the problem was delivered to me via Gmail. I had to read the prompt out of an email, then navigate between Gmail and Google Calendar — actually using the products — while screen-sharing the whole thing on Zoom. The interview was essentially: here are real production tools, here is a task that lives inside them, go.\n\nIt threw me at first because all my prep muscle memory is for a clean code editor with a problem statement pinned at the top. Once I adjusted it was fine, even kind of refreshing — it felt like the actual job.\n\nNeutral experience overall, did not move forward. Takeaway: fintech startups like this use production-tool-based coding assessments, not CoderPad. If you walk in expecting a sterile editor and get handed Gmail, the surprise alone can cost you the first ten minutes.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'SCREEN', rejectionYear:2024, userIndex:12 },

  // ── BREX ──
  { communityKey:'brex/swe', title:'Solved every phone-screen problem in time, rejected with zero feedback at a non-LeetCode company', body:`**Company**: Brex\n**Position**: Software Engineer\n**Stage**: Phone\n**Self-Analysis**: Non-LeetCode companies give you no surface area to prep against.\n\n---\n\nBrex, SWE phone screen. I will keep this focused because the lesson is specific.\n\nI passed phone screens at Google, LinkedIn, and Microsoft — the LeetCode-style gauntlet I had drilled hundreds of hours for. So when I hit the Brex phone screen and solved every problem they gave me within the time limit, I assumed I was through. Then: rejection, no feedback.\n\nThe thing that makes companies like Brex hard is not difficulty, it is unpredictability. They do not ask LeetCode. So you genuinely have no idea what they will ask. My entire prep apparatus was built for the FAANG style, and it transferred to the FAANG phone screens beautifully and to Brex not at all, even though I felt like I solved what was put in front of me.\n\nThe trap: at a LeetCode company, "I solved it in time" is a strong signal. At a non-LeetCode company, solving it might just be table stakes, and the real evaluation is on dimensions you did not even know were being graded.\n\nFor non-LeetCode companies, throw out the "did I get the answer" scorecard. Prep differently — practical projects, real debugging, clean idiomatic code under time pressure.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Software Engineer', interviewStage:'PHONE', rejectionYear:2024, userIndex:13 },

  // ── Y COMBINATOR ──
  { communityKey:'yc/s25', title:'W25 rejection after 5 drafts and 6 weeks — even strong founder referrals did not save it', body:`**Company**: Y Combinator\n**Position**: Founder (Smart Home Startup)\n**Stage**: Screen\n**Self-Analysis**: YC wants problems you have already solved, not problems you are still figuring out.\n\n---\n\nY Combinator W25, smart home startup. Rejected at the application stage. For context: 30K+ applications, under 1% accepted. I knew it was a lottery and still went all in.\n\nI wrote five full drafts over six weeks. Had good YC founder referrals — actual alumni who vouched for us. And we still did not get an interview.\n\nThe lesson took me a while to see. My early drafts were clever — they explained the vision, the market, the why-now. What they did not do was state, plainly and in one sentence, what we had built and what we had already proven. I was selling a story when YC wanted a fact.\n\nHere is the reframe that finally landed: YC wants problems you have already solved, not problems you are figuring out. My application was full of "we will" and "the plan is." It read like someone still mid-puzzle. The applications that get in read like "we built X, here is the traction, here is what we learned."\n\nSo: clarity over cleverness, evidence over vision, solved-it over solving-it.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Founder (Smart Home Startup)', interviewStage:'SCREEN', rejectionYear:2025, userIndex:14 },
  { communityKey:'yc/s25', title:'First YC rejection (S25): four concrete lessons beat one vague disappointment', body:`**Company**: Y Combinator\n**Position**: Founder (Travel Tech Startup)\n**Stage**: Screen\n**Self-Analysis**: Four concrete lessons beat one vague disappointment.\n\n---\n\nY Combinator S25, travel tech startup. First YC rejection. I am choosing to write it down clear-eyed instead of bitter.\n\nThe phrase I keep coming back to: this is not a setback, it is a setup. Not as a cope, but as an actual operating instruction.\n\nFirst, refine the pitch. My application tried to explain everything and therefore landed nothing. The next version says what we do in one line a stranger could repeat back, then earns the right to elaborate. Second, validate the assumptions. Half my market reasoning was assertion, not evidence — travelers want this, with no proof. Third, strengthen the team. YC bets on founders, and our story did not make clear why this specific team wins this specific market. Fourth, seek feedback — actively, from people who have been through it.\n\nNone of those four are about the idea being wrong. They are about the idea being under-proven and under-communicated. That is fixable.\n\nFirst rejection logged, four action items extracted. Setup, not setback.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Founder (Travel Tech Startup)', interviewStage:'SCREEN', rejectionYear:2025, userIndex:0 },
  { communityKey:'yc/s25', title:'Three profitable micro-SaaS as a solo founder. YC rejected me: no cofounder.', body:`**Company**: Y Combinator\n**Position**: Solo Founder (Micro-SaaS Portfolio)\n**Stage**: Screen\n**Self-Analysis**: YC has a recipe — not fitting it does not mean you are wrong.\n\n---\n\nY Combinator, solo founder. I run three profitable micro-SaaS products. Not pre-revenue — actually profitable, paying customers, money in the bank every month. I applied and got rejected, and the reason was clean and singular: no cofounder.\n\nYC's reasoning: "It is very hard to stay motivated for many years without a cofounder." Which is a real observation about the average founder. But I am not applying as a hypothetical — I am sitting on three businesses I already built and sustained, solo, through the unglamorous years where motivation supposedly dies. The evidence that I can stay motivated alone is the entire portfolio I just showed them.\n\nI sat with whether they are right. I landed here: YC has a recipe. Cofounders, a certain growth shape, a certain trajectory. The recipe works — it is why they are YC. But a recipe is a pattern that maximizes the average outcome, not a law of physics. Not fitting the recipe does not mean you are wrong; it means you are an exception their filter is not built to catch.\n\nNo bitterness. They optimized for their averages. If you do not fit the recipe, that is information about the recipe, not a referendum on you.\n\n---\n*Based on a real account, adapted for anonymity. / 실제 경험을 바탕으로 각색한 글입니다.*`, roleTitle:'Solo Founder (Micro-SaaS Portfolio)', interviewStage:'SCREEN', rejectionYear:2025, userIndex:1 },
]

async function main() {
  const sql = postgres(process.env.DATABASE_URL!, { ssl: 'require', max: 5 })

  // Check for YC community
  const ycComm = await sql`SELECT id FROM communities WHERE slug = 'investors/yc/s25'`
  if (ycComm.length > 0) COMMUNITY_IDS['yc/s25'] = ycComm[0].id as string
  else {
    const ycAny = await sql`SELECT id FROM communities WHERE slug LIKE 'investors/yc%' LIMIT 1`
    if (ycAny.length > 0) COMMUNITY_IDS['yc/s25'] = ycAny[0].id as string
  }

  console.log('Creating seed users...')
  const userIds: string[] = []
  for (const username of SEED_USERS) {
    const rows = await sql`
      INSERT INTO users (id, username, supabase_auth_id, karma)
      VALUES (${randomUUID()}, ${username}, ${randomUUID()}, 0)
      ON CONFLICT (username) DO UPDATE SET username = EXCLUDED.username
      RETURNING id
    `
    userIds.push(rows[0].id as string)
  }
  console.log(`Created ${userIds.length} users`)

  console.log(`Inserting ${POSTS.length} posts...`)
  let inserted = 0
  let skipped = 0
  for (const post of POSTS) {
    const communityId = COMMUNITY_IDS[post.communityKey]
    if (!communityId) { console.warn(`Skip — no community for: ${post.communityKey}`); skipped++; continue }
    const authorId = userIds[post.userIndex % userIds.length]
    await sql`
      INSERT INTO posts (id, title, body, community_id, author_id, vote_score, role_title, interview_stage, rejection_year)
      VALUES (
        ${randomUUID()}, ${post.title}, ${post.body},
        ${communityId}, ${authorId},
        ${Math.floor(Math.random() * 47)},
        ${post.roleTitle}, ${post.interviewStage}, ${post.rejectionYear}
      )
    `
    inserted++
    if (inserted % 10 === 0) process.stdout.write(`\r  ${inserted}/${POSTS.length} posts inserted`)
  }
  console.log(`\n\nDone! Inserted: ${inserted}, Skipped: ${skipped}`)
  await sql.end()
}
main().catch(console.error)
